catalog:
  services: # catalog must advertise at least one service
    - id: 525c5b5c-4e1d-4dbb-bea0-443d44a43b93
      name: ethereum-discovery-service
      description: Provides bootnode discovery to an Ethereum cluster
      bindable: true
      requires: [syslog_drain]
      tags:
        - ethereum
      metadata:
        displayName: Ethereum Discovery Service
        imageUrl: https://d1nwne6cc3e7hn.cloudfront.net/pivotal.png
        longDescription: The service binds to the RPC endpoint for an Ethereum cluster.
        providerDisplayName: Ethereum Discovery
        documentationUrl: https://github.com/micahyoung/ethereum-service-broker
        supportUrl: https://github.com/micahyoung/ethereum-service-broker
      plans: # a service has one or more plans
        - id: 3250c00a-e38d-44b2-ad63-9885cc13a80d
          name: public
          description: Ethereum Discovery
          metadata:
            bullets:
              - Ethereum
            costs:
              - amount:
                  usd: 0.0
                unit: MONTHLY
            displayName: Public

# credentials for Cloud Controller to authenticate with the broker
basic_auth:
  username: admin
  password: password
